### ISSUE TITLE
안녕하세요 올려주신 워크플로우 정말 잘 사용중인 사람입니다.

### ISSUE THREAD

**Issue by circumeo** [kw-lee/alfhanspell#1]
현재 올려주신 유니버설 액션으로 정말 편안하게 사용 중에 있습니다.
그런데 스페이스를 누르는 과정이 있어 수정된 결과물이 바로 출력되지 않아 불편하여 수정해 보려고 했지만 어떤 부분을 수정할지 몰라 글을 남겼습니다.
혹시 실례가 되지 않는다면 naver_spellcheck.py 파일 내에 어떤 부분을 수정해야 할지 가르쳐 주실 수 있을까요?

**Comment by kw-lee** [comment]
안녕하세요, 확인이 늦었습니다.
naver_spellcheck.py의 43번째 줄 아래부터 마지막 문자가 공백 문자인지 검사하는 부분을 제거해주시면 되겠습니다.
https://github.com/kw-lee/alfhanspell/blob/main/workflow/naver_spellcheck.py#L43

다만, 공백문자 없이 맞춤법검사를 시도할 경우 문장을 새로 고칠 때마다 요청을 새롭게 날리다보니 네이버 서버에 부담이 갈 수 있어 공백문자 입력을 사용하였습니다.
참고 부탁드립니다.

**Comment by circumeo** [comment]
> 안녕하세요, 확인이 늦었습니다. naver_spellcheck.py의 43번째 줄 아래부터 마지막 문자가 공백 문자인지 검사하는 부분을 제거해주시면 되겠습니다. https://github.com/kw-lee/alfhanspell/blob/main/workflow/naver_spellcheck.py#L43
> 
> 다만, 공백문자 없이 맞춤법검사를 시도할 경우 문장을 새로 고칠 때마다 요청을 새롭게 날리다보니 네이버 서버에 부담이 갈 수 있어 공백문자 입력을 사용하였습니다. 참고 부탁드립니다.

답변 감사합니다~
말씀해주신대로 44번에서 46번째 줄까지 삭제한후 실행했을경우 아무런 결과물이 나오지 않게됩니다 ㅠㅠ
혹시 참고가 될까하여 로그 기록을 남깁니다~

`[01:00:39.366] Logging Started...
[01:01:12.641] Spell Checker[Script Filter] Queuing argument '안녕하세요저는경기도에거주중인사람입니다'
[01:01:12.764] Spell Checker[Script Filter] Script with argv '(null)' finished
[01:01:12.771] ERROR: Spell Checker[Script Filter] Code 1: File "/Users/greedist/Library/Mobile Documents/com~apple~CloudDocs/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.EC06B984-4C41-4307-856F-8F91FCF46293/naver_spellcheck.py", line 45
    wf.add_item(
IndentationError: unexpected indent
  File "/Users/greedist/Library/Mobile Documents/com~apple~CloudDocs/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.EC06B984-4C41-4307-856F-8F91FCF46293/naver_spellcheck.py", line 45
    wf.add_item(
IndentationError: unexpected indent`

**Comment by kw-lee** [comment]
들여쓰기(indent) 관련 오류 같은데

```python
def main(wf):
    args = wf.args[0]

    # def wrapper():
    #     return get_spell_check_data(args)

    # res_json = wf.cached_data(args, wrapper, max_age=600)
    end_mark = re.search('\s+$', args)
    if end_mark:
        res_json = get_spell_check_data(args)
        out = f"{res_json['checked']}".rstrip()

        wf.add_item(
            title=out,
            subtitle="맞춤법 수정 결과 복사",
            arg=out,
            autocomplete=out,
            valid=True)

        wf.add_item(title=args,
                subtitle="원본 텍스트 복사",
                autocomplete=args,
                arg=args,
                valid=True)

        wf.send_feedback()
    else:
        wf.logger.debug("args: %s" % args)
        wf.add_item(title=u'문장 마지막에 반드시 공백을 1개 이상 입력해주세요.', valid=False)
        wf.send_feedback()
```

을 다음과 같이 수정하셔야할 것 같습니다.

```python
def main(wf):
    args = wf.args[0]

    # def wrapper():
    #     return get_spell_check_data(args)

    # res_json = wf.cached_data(args, wrapper, max_age=600)
    res_json = get_spell_check_data(args)
    out = f"{res_json['checked']}".rstrip()

    wf.add_item(
        title=out,
        subtitle="맞춤법 수정 결과 복사",
        arg=out,
        autocomplete=out,
        valid=True)

    wf.add_item(title=args,
            subtitle="원본 텍스트 복사",
            autocomplete=args,
            arg=args,
            valid=True)

    wf.send_feedback()
```

**Comment by circumeo** [comment]
> 들여쓰기(indent) 관련 오류 같은데
> 
> ```python
> def main(wf):
>     args = wf.args[0]
> 
>     # def wrapper():
>     #     return get_spell_check_data(args)
> 
>     # res_json = wf.cached_data(args, wrapper, max_age=600)
>     end_mark = re.search('\s+$', args)
>     if end_mark:
>         res_json = get_spell_check_data(args)
>         out = f"{res_json['checked']}".rstrip()
> 
>         wf.add_item(
>             title=out,
>             subtitle="맞춤법 수정 결과 복사",
>             arg=out,
>             autocomplete=out,
>             valid=True)
> 
>         wf.add_item(title=args,
>                 subtitle="원본 텍스트 복사",
>                 autocomplete=args,
>                 arg=args,
>                 valid=True)
> 
>         wf.send_feedback()
>     else:
>         wf.logger.debug("args: %s" % args)
>         wf.add_item(title=u'문장 마지막에 반드시 공백을 1개 이상 입력해주세요.', valid=False)
>         wf.send_feedback()
> ```
> 
> 을 다음과 같이 수정하셔야할 것 같습니다.
> 
> ```python
> def main(wf):
>     args = wf.args[0]
> 
>     # def wrapper():
>     #     return get_spell_check_data(args)
> 
>     # res_json = wf.cached_data(args, wrapper, max_age=600)
>     res_json = get_spell_check_data(args)
>     out = f"{res_json['checked']}".rstrip()
> 
>     wf.add_item(
>         title=out,
>         subtitle="맞춤법 수정 결과 복사",
>         arg=out,
>         autocomplete=out,
>         valid=True)
> 
>     wf.add_item(title=args,
>             subtitle="원본 텍스트 복사",
>             autocomplete=args,
>             arg=args,
>             valid=True)
> 
>     wf.send_feedback()
> ```

귀찮게 해드려서 죄송합니다..
덕분에 제가 하는 모든 작업의 효율이 세배는 좋아졌습니다 ^^
새해 복 많이 받으세요~
