### ISSUE TITLE
아이콘 변경 제안드려봅니다.

### ISSUE THREAD

**Issue by yellowphant** [kw-lee/alfhanspell#2]
안녕하세요.
맞춤법 검사 워크플로우를 다시 사용할 수 있게 수정해주셔서 감사히 잘 쓰고 있습니다.
워크플로우를 사용하다보니 다른 워크플로우와 같은 아이콘을 사용하고 있어서 제가 만든 아이콘을 제안드려봅니다.
혹시나 보시고 맘에 드신다면 적용해보시면 어떨까해서 글남깁니다. 
감사합니다.
혹시나 불쾌하셨다면 죄송합니다.

아이콘 파일 링크 https://yellow.d.pr/i/DCqNtM

**Comment by kw-lee** [comment]
제안 감사합니다! 상당히 급조해서 작성했던 워크플로우라 미처 아이콘을 신경쓰지 못했는데 기여해주셔서 감사합니다 😊
바로 반영해서 업데이트 하겠습니다.

**Comment by kw-lee** [comment]
커밋 https://github.com/kw-lee/alfhanspell/commit/4d41e97c4847a9709aa9a0309da613e2593c12f1 에서 반영하였고 v0.0.8으로 배포하였습니다 기여 감사합니다!!
